### ISSUE TITLE
Search result in the front page need to handle no result.

### ISSUE THREAD

**Issue by pureexe** [NeroYuki/KansenIndex-web#1]
First, I would like to Thank this project that contain ship-girl data from the game that I never heard of before. 

By the way, when I search for a ship that doesn't in the database, such as [Yoshino](https://wiki.wargaming.net/en/Ship:Yoshino). The website doesn't respond to anything. Can you make it at least say "Ship not found" or something that lets the user know the website is working correctly? 

You very much!

![image](https://github.com/user-attachments/assets/cd8a124b-6795-4720-ba36-d700a2316063)

**Comment by NeroYuki** [comment]
sure

![image](https://github.com/user-attachments/assets/063f03f0-0572-438e-8bbf-a9d24260d4ac)
